# Generated by Django 4.2.3 on 2025-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='media/profiles')),
                ('license_number', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
